### ISSUE TITLE
Detect precise position of first beat

### ISSUE THREAD

**Issue by nuthinking** [JMPerez/beats-audio-api#10]
Your algorithm works very well, thanks!

If I wanted to use the BPM for animation purposes I would need a precise position at least for the first beat. My understanding is that your peak positions are rounded by 0.5 seconds, which means not precise enough. Any idea how to do this? Perhaps a different process checking the soundwave? Thanks!

**Comment by JMPerez** [comment]
@nuthinking Decreasing the value of  `partSize` in https://github.com/JMPerez/beats-audio-api/blob/a3254ef4ab9c84397bbadbe109f12be9c8d7e642/script.js#L71 should give you more parts, and hopefully more precision.

The reason for the current values is htat those are the ones used by [the post this project is based on](http://joesul.li/van/beat-detection-using-web-audio/).

**Comment by nuthinking** [comment]
Thanks a lot @JMPerez! Decreasing the partSize indeed gives me more precision and doesn't seem to affect the calculation.
Only thing I noticed, and I guess could be hard to fix, is to detect a BPM with decimals. Tried to round to 0.2 but it breaks.

**Comment by JMPerez** [comment]
That might be more difficult due to how the distance between peaks is grouped https://github.com/JMPerez/beats-audio-api/blob/gh-pages/script.js#L120-L145

The more precision the more likely it is to not find groups with exactly the same distance, thus making the calculation difficult. I guess it's a matter of playing with the values and seeing which ones work best in your case.

I'll close the ticket in the meanwhile to do some clean up, since the first bit was solved.
