### ISSUE TITLE
SoundCloud integration

### ISSUE THREAD

**Issue by splinter7** [JMPerez/beats-audio-api#2]
I'm interested in integrating this with soundcloud and not spotify. I've tried removing the spotify and echonest functions and just add a soundcloud search instead. This hasn't yielded any positive results nor has it given me an error. Is it possible you can give a little insight

**Comment by JMPerez** [comment]
@splinter7 I'm not familiar with Soundcloud's API. Does it expose MP3 files? If so, it should be possible to do the same thing I'm doing, but on those MP3 files.

Also, I would appreciate if you could fork the project and link to it so I can try it.

**Comment by joshcawthorne** [comment]
Is there any possibility of you showing me how to add a pause button to the code? I can't work out how you're playing the audio really as I'm new to all of this!

Cheers!

**Comment by sublimescapes** [comment]
Has there been any update on this? @JMPerez as far as I know, soundcloud doesn't directly expose mp3 files. 

But there's a little JS bookmarklet for so. 
https://gist.github.com/pheuter/1980967

**Comment by JMPerez** [comment]
@sublimescapes I used Spotify because I have experience with it and wanted to get MP3s on which I could calculate the BPM. I don't know whether Soundcloud exposes MP3s, and I honestly don't plan on working on including it myself.

The point of the project is to show how, given an audio file, one could calculate its BPM, and not necessarily including support for multiple music streaming services.
